// Extension for Chrome Browser - Magic Actions for YouTube™ - CHROMEACTIONS.COM - Copyright 2015 Vlad and Serge Strukoff - All Rights Reserved
window.addEventListener("load",magicOpt,!1);
function magicOpt(){function B(m){C(m.url);a=m.opt;m=document.createDocumentFragment();var b;b=f("ul");b.id="opt";m.appendChild(b);if(0<a.nv){var x=chrome.i18n.getMessage("m1",[D,a.ver]);t(b,x);setTimeout(function(){window.top.postMessage(x,"http://www.chromeactions.com")},1500);l("nv",0)}t(b,"YouTube constantly make changes, and we constantly need to make sure we are in sync. Last years we have been working hard to provide you with the best possible features.<br>Due to the very, very small number of donations the project may be closed.<br>If you like our app, please support further development with a <u>Donation</u>.",!1,
!0);d(b,"mwvc",c("o8"),a.mwvc,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-volume-control.html");E(b);F(b);G(b);H(b,"gap",c("o27"),a.gap,1,25,1,!a.mwvc);d(b,"hq",c("o90"),a.hq,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-autohd.html");I(b);d(b,"ha",c("o20"),a.ha);d(b,"wide",c("o28"),a.wide);d(b,"ww",c("o80"),a.ww);d(b,"cin",c("o29"),a.cin,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-cinema.html");J(b);d(b,"cina",c("o30"),a.cina,1,!a.cin);d(b,"cinf",c("o31"),
a.cinf,1,!a.cin);d(b,"pt",c("o65"),a.pt);pti=a.pti;K(b);d(b,"pause",c("o17"),a.pause);d(b,"plist",c("o19"),a.plist,1,!a.pause);d(b,"buf",c("o18"),a.buf);d(b,"buf1",c("o63"),a.buf1,1,!a.buf);d(b,"loop",c("o40"),a.loop);d(b,"hide",c("o41"),a.hide);d(b,"c0",c("o70"),a.c0,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-comments.html");u(b,["c1",c("o71"),a.c1,"c4",c("o86"),a.c4,"c3",c("o73"),!1],!a.c0);d(b,"anns",c("o42"),a.anns);d(b,"f0",c("o43"),a.f0);d(b,"h0",c("o50"),a.h0);u(b,["h7",c("o56"),
a.h7,"h1",c("o51"),a.h1,"h2",c("o52"),a.h2,"h3",c("o53"),a.h3,"h4",c("o54"),a.h4],!a.h0);u(b,["h5",c("o55"),a.h5,"h6",c("o64"),a.h6],!a.h0);d(b,"a0",c("o60"),a.a0,0,0,"http://www.chromeactions.com/magic-actions-for-youtube-themes.html");d(b,"a4",c("o81"),a.a4,1,!a.a0);d(b,"a1",c("o61"),a.a1,1,!a.a0);d(b,"a2",c("o62"),a.a2,1,!a.a0);d(b,"a3",c("o84"),a.a3,1,!a.a0);d(b,"a5",c("o85"),a.a5,1,!a.a0);document.body.appendChild(m);document.getElementById("f0").parentElement.title="Show/Hide the Filters button so you can apply a filter (grayscale, flip, high contrast etc.) to any video";
L("a5")}function l(a,b){chrome.runtime.sendMessage(JSON.stringify({id:4,name:a,value:b}))}function L(a){var b=f("sup");b.textContent=c("m4");b.style.color="red";b.style.verticalAlign="top";document.getElementById(a).nextElementSibling.appendChild(b)}function M(c){document.getElementById(a.color).className="";a.color=this.id;this.className="sel";l("color",a.color)}function y(c){document.getElementById("vt"+a.mwvct).checked=!1;a.mwvct=parseInt(this.id.charAt(2));this.checked=!0;l("mwvct",a.mwvct)}function v(c){document.getElementById("vc"+
a.mwvci).checked=!1;a.mwvci=parseInt(this.id.charAt(2));this.checked=!0;l("mwvci",a.mwvci)}function w(c){document.getElementById("ca"+a.cini).checked=!1;a.cini=parseInt(this.id.charAt(2));this.checked=!0;l("cini",a.cini)}function z(c){document.getElementById("pt"+a.pti).checked=!1;a.pti=parseInt(this.id.charAt(2));this.checked=!0;l("pti",a.pti)}function k(c){document.getElementById(a.hqi).checked=!1;a.hqi=this.id;this.checked=!0;l("hqi",a.hqi)}function A(a){if("c3"==this.id)this.checked=!1,this.disabled=
!0,t(document.body,'<b>Note:</b> The Country Flags feature was disabled due to the YouTube <a target="_blank" href="https://developers.google.com/youtube/youtube-api-list">deprecation policy</a>.<br>The YouTube API v2 would be retired in April 20, 2015, and would be shut down soon thereafter.',!0);else if(l(this.id,this.checked),a=this.parentElement,"opt"==a.className)for(a=a.nextElementSibling;a&&("sub"==a.className||"sub multi"==a.className);)a.setAttribute("disabled",!this.checked),a=a.nextElementSibling}
function N(a){l(a.id,parseInt(a.value))}function O(a){s&&(clearTimeout(s),s=0);this.nextElementSibling.textContent=this.value;s=setTimeout(N,1E3,this)}function F(m){var b,d,e="red LightPink orange lime GreenYellow yellow gold DodgerBlue aqua magenta DeepPink white".split(" "),r=f("li");b=f("label");r.className="sub";r.setAttribute("disabled",!a.mwvc);r.id="color";b.textContent=c("o9");r.appendChild(b);for(var h=0,g=e.length;h<g;h++)d=e[h],b=f("button"),b.id=d,b.style.backgroundColor=d,a.color==d&&
(b.className="sel"),r.appendChild(b),b.addEventListener("click",M,!1);m.appendChild(r)}function E(m){var b=f("li");b.id="mwvct";b.className="sub";b.setAttribute("disabled",!a.mwvc);e(b,"vt0",c("o82"),0==a.mwvct,y);e(b,"vt1",c("o83"),1==a.mwvct,y);m.appendChild(b)}function G(m){var b=f("li"),d=f("label");b.id="mwvci";b.className="sub";b.setAttribute("disabled",!a.mwvc);d.textContent=c("o23");b.appendChild(d);e(b,"vc1",c("o24"),1==a.mwvci,v);e(b,"vc2",c("o25"),2==a.mwvci,v);e(b,"vc0",c("o26"),0==a.mwvci,
v);m.appendChild(b)}function J(m){var b=f("li"),d=f("label");b.id="cini";b.className="sub";b.setAttribute("disabled",!a.cin);d.textContent=c("o32");b.appendChild(d);e(b,"ca0",c("o33"),0==a.cini,w);e(b,"ca1",c("o34"),1==a.cini,w);e(b,"ca2",c("o35"),2==a.cini,w);m.appendChild(b)}function K(m){var b=f("li");b.id="pti";b.className="sub";b.setAttribute("disabled",!a.pt);e(b,"pt0",c("o66"),0==a.pti,z);e(b,"pt1",c("o67"),1==a.pti,z);m.appendChild(b)}function e(a,b,c,d,e){var h=f("label"),g=f("input");g.type=
"radio";g.id=b;d&&(g.checked=!0);a.appendChild(g);h.textContent=c;h.setAttribute("for",b);a.appendChild(h);g.addEventListener("click",e,!1)}function I(d){var b=f("li");b.id="hqi";b.className="sub";b.setAttribute("disabled",!a.hq);e(b,"highres",c("o91"),"highres"==a.hqi,k);e(b,"hd2880",c("o92"),"hd2880"==a.hqi,k);e(b,"hd2160",c("o93"),"hd2160"==a.hqi,k);e(b,"hd1440",c("o94"),"hd1440"==a.hqi,k);e(b,"hd1080",c("o95"),"hd1080"==a.hqi,k);e(b,"hd720",c("o96"),"hd720"==a.hqi,k);e(b,"large",c("o97"),"large"==
a.hqi,k);e(b,"medium",c("o98"),"medium"==a.hqi,k);e(b,"small",c("o99"),"small"==a.hqi,k);e(b,"tiny",c("o100"),"tiny"==a.hqi,k);d.appendChild(b)}function d(a,b,c,d,e,h,g){var q=f("li"),k=f("label"),n=f("input");k.textContent=c;k.setAttribute("for",b);n.type="checkbox";n.id=b;n.checked=d;q.appendChild(n);q.appendChild(k);e?(q.className="sub",q.setAttribute("disabled",h)):q.className="opt";g&&(b=f("a"),b.href=g,b.setAttribute("target","_blank"),b.className="help",q.appendChild(b));a.appendChild(q);n.addEventListener("click",
A,!1)}function u(a,b,c){for(var d=f("li"),e,h,g=0,k=b.length;g<k;g+=3)e=f("label"),h=f("input"),e.textContent=b[g+1],e.setAttribute("for",b[g]),h.type="checkbox",h.id=b[g],h.checked=b[g+2],d.appendChild(h),d.appendChild(e),h.addEventListener("click",A,!1);d.className="sub multi";d.setAttribute("disabled",c);a.appendChild(d)}function H(a,b,c,d,e,h,g,k){var l=f("li"),n=f("label"),p=f("input");n.textContent=c;n.setAttribute("for",b);p.type="range";p.min=e;p.max=h;p.step=g;p.value=d;p.id=b;p.title="Range: "+
e+"-"+h;l.appendChild(n);l.appendChild(p);n=f("span");n.textContent=d;l.appendChild(n);l.className="sub";l.setAttribute("disabled",k);a.appendChild(l);p.addEventListener("change",O,!1)}function t(a,b,c,d){var e=f("ul"==a.localName?"li":"div");e.className="msg"+(c?" fixed":"");e.innerHTML=b;a.appendChild(e);e.addEventListener("click",d?P:Q,!1)}function P(){chrome.runtime.sendMessage(JSON.stringify({id:2,url:"http://www.chromeactions.com/app/donate.php"}))}function Q(a){this.parentElement.removeChild(this);
a.stopPropagation()}function C(a){0!=a.indexOf("http://www.chromeactions.com/")&&0!=a.indexOf(chrome.runtime.getURL(""))&&0!=a.indexOf("https://www.chromeactions.com/")&&(document.location.href="about:blank")}function f(a){return document.createElement(a)}function c(a){return chrome.i18n.getMessage(a)}if(chrome.tabs&&window.location.search!="?s=687"+(new Date).getDate())window.location.href="options.html";else{var a,s=0,D=chrome.i18n.getMessage("extName");chrome.runtime.sendMessage('{"id":0}',B)}}
;
