function hasNever(a,b,d,c){var f=a=lpcanonizeUrl(a);0<a.length&&"/"==a.charAt(a.length-1)&&(a=a.substring(0,a.length-1));if(g_neverurls[d]&&0<g_neverurls[d].length){for(var e=!1,g=0;g_neverurls[d]&&g<g_neverurls[d].length;g++){var h=g_neverurls[d][g];if(h==b||h==a){e=!0;break}}if(!e)return!0}for(g=0;g_neverurls[c]&&g<g_neverurls[c].length;g++)if(h=g_neverurls[c][g],h==b||h==a||h==f)return!0;return!1}function hasNeverAutologin(a,b){return hasNever(a,b,"onlyautologins","neverautologins")}
function hasNeverFormFill(a,b){return hasNever(a,b,"onlyformfills","neverformfills")}function hasNeverSave(a,b){return hasNever(a,b,"onlyaccounts","neveraccounts")}function hasNeverShowIcon(a,b){return hasNever(a,b,"onlyshowicons","nevershowicons")}function hasNeverGenerate(a,b){return hasNever(a,b,"onlygenerates","nevergenerates")}var g_accessibility_enabled=-1;
function handleFill(a,b){var d=!1,c=null;if((!lploggedin||null!=grid_getdata("active"))&&!skiplogin()||("undefined"==typeof b||!b)||!check_for_frame_mismatch_ok(a,b.fromiframe,gs("Are you sure you would like your LastPass site information to be filled into the following site?"),b.cmd))return!1;g_fillfield_did_fillbest[a.toString()]=!1;if("autofillaid"==b.cmd||"autologinaid"==b.cmd){var f=b.aid;g_last_launch[f]=(new Date).getTime();if("undefined"!=typeof g_sites[f]){var d="autologinaid"==b.cmd,e=!0,
g=get_record(f);b.no_manualfill_on_saveall&&g.save_all&&(e=!1);b.from_iframe&&!g.save_all&&(e=!0);c=b.from_iframe?!0:!1;g_fillfield_confirm_perfield={};fill({tabid:a,acct:g_sites[f],docid:null,submit:d,doconfirm:!d,docnum:"all",allowforce:!0,skip_pwprotect:!1,manualfill:e,automaticallyFill:null,skip_basicauth:null,from_iframe:c,desc:b.cmd});return!0}return!1}if("undefined"==typeof b.url)return!1;"undefined"!=typeof b.username_val&&(g_username_vals[b.url]=b.username_val);var e=b.url,h=lp_gettld_url(e);
if(lp_url_is_lastpass(e))return!1;if("undefined"==typeof g_launches[a]||!g_launches[a])null!=g_pending_launch&&(g_launches[a]=g_pending_launch);"undefined"!=typeof g_launches[a]&&g_launches[a]&&(f=g_launches[a],"undefined"!=typeof g_sites[f]&&(g=get_record(f),g_fillfield_confirm_perfield={},check_ident_aid(f)&&compare_tlds(h,lp_gettld_url(g_sites[f].url))&&(is_guiless()?fill({tabid:a,acct:g,docid:null,submit:!1,doconfirm:!1,docnum:"all",allowforce:!0,skip_pwprotect:!1,manualfill:!1,automaticallyFill:!1,
desc:"FILL_F2"}):(c=b.from_iframe?!0:!1,fill({tabid:a,acct:g,docid:null,submit:!0,doconfirm:!1,docnum:b.docnum,allowforce:!1,skip_pwprotect:!0,manualfill:null,automaticallyFill:null,skip_basicauth:null,from_iframe:c,desc:"FILL_F3"}),c=f),"undefined"!=typeof b.numpass&&0<b.numpass?g_pending_launch=g_launches[a]=null:setTimeout(function(){g_pending_launch=g_launches[a]=null},1E3))));var k=getsites(h),k=reorderOnURL(k,e,!0);hasNeverAutologin(e,h)&&(k=[]);g=b.topurl!=e?lp_gettld_url(b.topurl):"";""!=
g&&hasNeverAutologin(b.topurl,g)&&(k=[]);for(var s in k){try{if(islastpass&&g_ischrome&&1==k[s].basic_auth&&0>=g_accessibility_enabled&&0==lpGetPref("basicauthnever",0))if(g_is_mac&&have_binary_function("accessibility_enabled"))call_binary_function("accessibility_enabled",function(a){g_accessibility_enabled=a?1:0;0==g_accessibility_enabled&&setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:0,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to enable access for assistive devices.")})})},
100)});else if((g_is_win||g_is_mac)&&!have_binary())g_accessibility_enabled=0,setTimeout(function(){get_selected_tab(null,function(a){sendCS(gettabid(a),{cmd:"showbasicauthnotification",needbinary:1,text:gs("In order for LastPass to fill into basic authentication dialogs, you need to install the binary version of LastPass for Chrome.")})})},100)}catch(r){}h=!1;f=k[s].aid;if(check_ident_aid(f)&&"undefined"!=typeof g_sites[f]&&(g=get_record(f))){g.never_autofill&&(h=!0);if(g.pwprotect||g_prompts.login_site_prompt)h=
!0;if(!g.genpw&&!(0==g.fields.length&&""==g.username)){0==g.url.indexOf("https://")&&0!=e.indexOf("https://")&&(h=!0);g_fillfield_confirm_perfield={};0==parseInt(lpGetPref("automaticallyFill",1))&&0==parseInt(lpGetPref("highlightFields",1))&&(h=!0);if(!h){if(c&&c!=f){verbose_log("did_launched_aid != aid "+c+"!="+f);continue}if(f=!g.save_all)"undefined"==typeof g_fillfieldsmatches[e]&&(g_fillfieldsmatches[e]=[]),g_fillfieldsmatches[e][g_fillfieldsmatches[e].length]=g,g_fillfieldsmatchescurridx[e]=
0;s=parseInt(lpGetPref("automaticallyFill",1));fill({tabid:a,acct:g,docid:b.docid,submit:null,doconfirm:f,docnum:b.docnum,allowforce:null,skip_pwprotect:!0,manualfill:null,automaticallyFill:s,desc:"FILL_F4"})}0!=lpGetPref("showFillNotificationBar",1)&&(get_selected_tab(null,function(){sendCS(a,{cmd:"showfillnotification",text:gs("LastPass has filled your login information into the form on this page."),sites:cache_usernames(k),docnum:b.docnum})}),d=!0);break}}}!d&&0==lpGetPref("showNotificationsAfterClick",
1)&&checkgenpwfillforms(a,e);return!0}
function checkWeakDuplicateBreached(a,b,d){if(g_showweakdupalerts&&qualifyForWeakCheck(getpasswordfromacct(a))&&(g_ischrome||g_issafari))!1==g_disablepwalerts&&("undefined"==typeof a.noalert||"1"!=a.noalert)&&getWeakAndDuplicateIds(g_username_hash,g_username,function(c){var f=null!=a.sharedfromaid&&""!=a.sharedfromaid&&"0"!=a.sharedfromaid&&"null"!=a.sharedfromaid?1:0,e=issharedfolder(g_shares,a.group),e=!checkreadonly(e,!0),f=!f&&!e&&"1"==a.pwch?1:0;isBreachedSite(a)?(g_notification_type="lpalert",
g_badgedata={cmd:"notification",type:"lpalert"},g_notification_data={cmd:"notification",type:"lpalert",data:{lpa_title:gs("This site was affected by a breach!"),lpa_msg:gs("The account you are logging into was either hacked or was reusing a password a password from a site that was hacked. You should take action now to change this password"),lpa_secondary_msg:gs("Use the Security Challenge to see other affected sites"),lpa_onclicktext:gs("Change Passwords Now"),lpa_onclickurl:base_url+"misc_challenge.php?breachid="+
a.breached}},set_badge(g_notification_data,b),drawIconAtRotation(0)):isDuplicateSite(c[0],a.aid)?(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:a.aid,name:a.name,username:getusernamefromacct(a),alerttype:"duplicate",tld:d,tabid:b,pwch:f},set_badge(g_notification_data,b),drawIconAtRotation(0)):isWeakPassword(c[1],a.aid)&&(g_notification_type="alert",g_notification_data={cmd:"notification",type:"alert",aid:a.aid,name:a.name,username:getusernamefromacct(a),alerttype:"weak",
tld:d,tabid:b,pwch:f},set_badge(g_notification_data,b),drawIconAtRotation(0))})}
function checkgenpwfillforms(a,b,d){var c=lp_gettld_url(b),f=1!=lpGetPref("showGenerateNotifications",1)||hasNeverGenerate(b,c),e=1!=lpGetPref("showFormFillNotifications",1)||hasNeverFormFill(b,c),g=[];if(do_experimental_popupfill){for(var h=0;h<g_formfills.length;h++)check_ident_ffid(g_formfills[h].ffid)&&(g[g.length]=g_formfills[h]);0==g.length&&(e=!0);b={cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:e,sites:cache_usernames(reorderOnURL(getsites(c),b,!0,!0)),formfills:LPJSON.stringify(g),
active:g_popupfill_last_active[a],activefieldid:g_popupfill_last_active_fieldid[a]};d||(b.ff=g_cachedffdat);sendCS(a,b,"all")}else{if(!e){for(h=0;h<g_formfills.length;h++)check_ident_ffid(g_formfills[h].ffid)&&(g[g.length]=g_formfills[h]);0==g.length&&(e=!0)}if(!f||!e)b={cmd:"checkgenpwfillforms",nevergenerate:f,neverformfill:e,sites:cache_usernames(reorderOnURL(getsites(c),b,!0,!0)),formfills:LPJSON.stringify(g)},d||(b.ff=g_cachedffdat),sendCS(a,b,"all")}}
function cache_usernames(a){for(var b in a)a[b].useusername=getusernamefromacct(a[b]);return LPJSON.stringify(a)}
function handleNever(a,b){if("neverautofill"==b.cmd){var d=b.aid;if("undefined"==typeof g_sites[d])return;g_sites[d].never_autofill=!0;g_sites[d].autologin=!1;d="aid="+en(d);lpMakeRequest(base_url+"set_never_autofill.php",d,null,null)}else if("neverdomain"==b.cmd||"neverpage"==b.cmd){var c="neverdomain"==b.cmd?lp_gettld_url(b.url):lpcanonizeUrl(b.url),d="url="+en(AES.url2hex(c));"undefined"!=typeof b.fromsave&&b.fromsave?g_neverurls.neveraccounts.push(c):"undefined"!=typeof b.fromgenerate&&b.fromgenerate?
(d+="&type=1",g_neverurls.nevergenerates.push(c)):"undefined"!=typeof b.fromformfill&&b.fromformfill?(d+="&type=2",g_neverurls.neverformfills.push(c)):"undefined"!=typeof b.fromshowicons&&b.fromshowicons?(d+="&type=6",g_neverurls.nevershowicons.push(c)):"undefined"!=typeof b.neverforall&&b.neverforall?(g_neverurls.neveraccounts.push(c),g_neverurls.nevergenerates.push(c),g_neverurls.neverformfills.push(c),g_neverurls.neverautologins.push(c),g_neverurls.nevershowicons.push(c),d+="&type=7"):(d+="&type=3",
g_neverurls.neverautologins.push(c));lpMakeRequest(base_url+"add_never.php",d,null,null)}g_local_accts_version++;rewritelocalfile()}
function handleSave(a,b){function d(a){if(!a)return!1;var b=["text","email","tel","url"],c;for(c in b)if(b.hasOwnProperty(c)&&a==b[c])return!0;return!1}var c=!1;if(g_cpwbot&&CPWbot_bg&&a==CPWbot_bg.get_pwchangetabid())return L("handleSave(tab:"+a+", state="+CPWbot_bg.g_pwchangestate+")"),console_log("Skipping save because driving a password change"),!1;var f=get_ff_translation("ff_currpass_regexp");if("undefined"==typeof SAVEALLFORMSUBMITS&&(!lploggedin||lp_url_is_lastpass(b.url,!0)||lp_url_is_lastpassext(b.url)))return!1;
for(var e=b.formdata.split("\n"),g=!1,h=!1,k=null,s="",r="",q=[],j=[],t=0,u=0,m=0,n=0,x=0,p=0;p<e.length;p++){var l=e[p].split("\t");if(!(4!=l.length&&5!=l.length)){decodeURIComponent(l[2]);var z=l[3];"password"==z?t++:"hidden"==z?x++:d(z)&&u++;"password"==z&&(5>l.length||5<=l.length&&"seen"==l[4])?m++:d(z)&&(5>l.length||5<=l.length&&"seen"==l[4])&&n++}}for(u=0;u<e.length;u++)if(n=e[u],n=n.split("\t"),!(4!=n.length&&5!=n.length)){l=decodeURIComponent(n[2]);x=n[3];p=!0;g&&(5<=n.length&&"notseen"==
n[4])&&(p=!1);if((!g||!h)&&d(x)&&0<l.length)p&&(s=l,g=!0),!1==h&&"undefined"!=typeof SpecialSites[lpcanonizeUrl(b.url)]&&(h=!0);if(!("password"==x&&5<=n.length&&"notseen"==n[4]&&1<t&&0<m)&&"password"==x&&(p||!1==h))if(p=decodeURIComponent(n[1]),q[j.length]={name:p,value:l},j[j.length]=l,!h&&l.length&&(r=l,h=!0),null==k&&(l=RegExp(f,"i"),p&&(p==b.current_pw_field_name||l.exec(p))))k=j.length-1}if(h){b.username=s;b.password=r;!g&&1<j.length&&(j[0]!=j[1]&&null==k)&&(b.username=j[0],b.password=j[1]);
f=lp_gettld_url(b.url);b.tld=f;n=!1;h="";1<j.length&&j[j.length-1]==j[j.length-2]&&""!=j[j.length-1]&&q[j.length-1].name!=q[j.length-2].name?(n=!0,h=j[j.length-1]):1<j.length&&j[0]==j[1]&&""!=j[0]&&q[0].name!=q[1].name?(n=!0,h=j[0]):1<j.length&&(j[0]!=j[1]&&""!=j[0]&&null!=k)&&(h=0==k&&2==j.length?j[1]:1==k&&2==j.length?j[0]:"");q=n||null!=k&&h;k=[];if(q&&(k=getsites(f,!0),b.createacct=2==j.length||0<array_length(k),b.createacct)){z=m=t=j="";for(u=0;u<e.length&&!(n=e[u],n=n.split("\t"),!(4!=n.length&&
5!=n.length)&&(x=n[3],""==j&&(d(x)&&""!=n[1]&&""!=n[2])&&(p=decodeURIComponent(n[1]),l=get_ff_translation("ff_username_regexp"),""!=l&&(l=RegExp(l,"i"),l.exec(p)&&(j=p,t=decodeURIComponent(n[2])))),""==m&&(d(x)&&""!=n[1]&&""!=n[2])&&(p=decodeURIComponent(n[1]),x=get_ff_translation("ff_email_regexp"),""!=x&&(l=RegExp(x,"i"),l.exec(p)&&(m=p,z=decodeURIComponent(n[2])))),""!=j&&""!=m));u++);""==j&&(j=m,t=z);b.username_field=j;""!=t&&(b.username=t)}if(q&&0<array_length(k)){if(verbose_log("looking for newpw="+
(g_show_pw_in_logs||g_isadmin?h:"REDACTED")+" tld="+f+" in g_didchangepw"),g="undefined"!=typeof g_didchangepw[SHA256(h+f)]&&g_didchangepw[SHA256(h+f)]>(new Date).getTime()-6E5,verbose_log("already processed pw ="+(g_show_pw_in_logs||g_isadmin?h:"REDACTED")+" tld="+f+" is "+g),!g&&(g_notification_type="change",b.newpw=h,g_notification_data=b,sendTS({cmd:"notification",type:"change"}),c=!0,0!=lpGetPref("showChangeNotificationBar",1))){var e=k,v;b.sitecount=array_length(e);if(1==array_length(e))for(u in e){b.singleaid=
u;v=gs("LastPass detected a password change for user:")+" "+getusernamefromacct(g_sites[u]);break}else v=gs("LastPass detected a password change for domain:")+" "+f;sendCS(a,{cmd:"showchangenotification",text:v,notificationdata:b});g_persistent_notifications[a]={cmd:"showchangenotification",text:v,notificationdata:b}}}else{if(hasNeverSave(b.url,f))return!1;var e=getsites(f),w;for(w in e)if(check_ident_aid(w)&&"undefined"!=typeof g_sites[w]&&(v=get_record(w),e=getusernamefromacct(v),u=getpasswordfromacct(v),
(!g||s==lpmdec_acct(v.username,!0,v,g_shares)||0==s.indexOf("****")||s==e)&&(r==lpmdec_acct(v.password,!0,v,g_shares)||r==u)||v.save_all&&isMatch(v,g,s,r)||s==lpmdec_acct(v.username,!0,v,g_shares)&&""==r))return!1;g_notification_type="save";g_notification_data=b;0!=lpGetPref("showSaveSiteNotifications",0)&&(sendTS({cmd:"notification",type:"save"}),c=!0);0!=lpGetPref("showSaveNotificationBar",1)&&lpCheckAddSite(b.username,b.password,f)&&(g_persistent_notifications[a]={cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),
notificationdata:LPJSON.stringify(b)},sendCS(a,{cmd:"showaddnotification",text:gs("Should LastPass remember this password?"),notificationdata:LPJSON.stringify(b)},"streetscape.com"==f?"all":null),c=!0)}}return c}
function lpCheckAddSite(a,b,d){var c=lp_get_gmt_timestamp(),f=[],e;for(e in g_rejectedaddsites){var g=g_rejectedaddsites[e];c>g.rejectedTime+600&&(f[f.length]=e)}for(e=f.length-1;0<=e;e--)g_rejectedaddsites.splice(f[e],1);for(e in g_rejectedaddsites)if(g=g_rejectedaddsites[e],g.username==a&&lpdec(g.encryptedPassword)==b&&compare_tlds(g.tld,d))return!1;return!0}var lastupdatefields="";
function handleUpdateFields(a,b){var d=b.aid,c=g_sites[d],f=issharedfolder(g_shares,c.group);if(checkreadonly(f,!0)){var e=[],g=[],h=updateAndEncryptData(b.formdata,e,g,c),k=SHA256(h);if(k!=lastupdatefields){lastupdatefields=k;update_username_from_fields_if(c,e);for(k=c.fields.length-1;0<=k;k--)!c.fields[k].otherfield&&"1"!=c.fields[k].otherlogin&&c.fields.splice(k,1);for(k=0;k<e.length;k++)c.fields[c.fields.length]=e[k];g_local_accts_version++;rewritelocalfile();d="data="+en(bin2hex(h))+"&ref="+
en(url2hex(b.url))+"&updatefields=1&aid="+en(d);d+=!1==f?"":"&sharedfolderid="+en(f.id);c.postdata=d;c.posturl=base_url+"gm_deliver.php";c.newvalues=g;updateFieldsFromSubmit(d,c)}}}
function handleAddUrid(a,b){var d=b.aid,c=g_sites[d],f=issharedfolder(g_shares,c.group);if(checkreadonly(f,!0)){for(var e=[],g=0;g<c.fields.length;g++)"1"==c.fields[g].otherlogin&&!lp_in_array(c.fields[g].urid,e)&&(e[e.length]=c.fields[g].urid);if(!(10<=e.length)){var h=[],e=[],k=updateAndEncryptData(b.formdata,h,e,c);update_username_from_fields_if(c,h);for(g=0;g<h.length;g++)h[g].otherlogin="1",h[g].url=url2hex(b.url),c.fields[c.fields.length]=h[g];g_local_accts_version++;rewritelocalfile();d="data="+
en(bin2hex(k))+"&ref="+en(url2hex(b.url))+"&addurid=1&aid="+en(d);d+=!1==f?"":"&sharedfolderid="+en(f.id);c.postdata=d;c.posturl=base_url+"gm_deliver.php";c.newvalues=e;updateFieldsFromSubmit(d,c)}}}
function update_username_from_fields_if(a,b){for(var d=get_ff_translation("ff_combineddummy_regexp"),c=RegExp(d,"i"),f=0,d="",e=0;e<b.length;e++)if("text"==b[e].type||"email"==b[e].type||"tel"==b[e].type||"url"==b[e].type)if(!c.exec(b[e].name)&&!c.exec(b[e].id)&&!("answer"==b[e].id||"answer"==b[e].name))if(d=b[e].value,2<=++f)break;if(1==f&&""!=d){for(e=c=0;e<a.fields.length;e++)if(!a.fields[e].otherfield&&("text"==a.fields[e].type||"email"==a.fields[e].type||"tel"==a.fields[e].type||"url"==a.fields[e].type)){c++;
break}0==c&&(a.username=d,a.unencryptedUsername=lpdec_acct(crypto_btoa(a.username),a,g_shares))}}function handleSaveAll(a,b){b.save_all=1;g_site_data=b;openURL(getchromeurl("site.html"))}
function isMatch(a,b,d,c){b=b?!1:!0;for(var f=!1,e=0;e<a.fields.length;e++)if(!("text"!=a.fields[e].type&&"password"!=a.fields[e].type&&"email"!=a.fields[e].type&&"tel"!=a.fields[e].type&&"url"!=a.fields[e].type)){var g=lpmdec_acct(a.fields[e].value,!0,a,g_shares);if(("text"==a.fields[e].type||"email"==a.fields[e].type||"tel"==a.fields[e].type||"url"==a.fields[e].type)&&d==g)b=!0;"password"==a.fields[e].type&&c==g&&(f=!0)}return b&&f?!0:!1}var g_reqindex=0;
function fill(a){var b=a.tabid,d=a.acct;if(!b||!d)return!1;var c=a.docid,f=a.submit,e=a.doconfirm,g=a.docnum,h=a.allowforce,k=a.skip_pwprotect,s=a.skip_basicauth,r=a.from_iframe,q=a.desc,j=a.manualfill;j||(j=!1);var t=a.automaticallyFill;if("undefined"==typeof t||null==t)t=1;write_history({cmd:q,aid:d.aid,submit:f,doconfirm:e,allowforce:h});verbose_log("tabid="+b+"\nacct.aid="+d.aid+"\ndocid="+c+"\nsubmit="+f+"\ndoconfirm="+e+"\ndocnum="+g+"\nallowforce="+h+"\nskip_pwprotect="+k+"\nmanualfill="+j+
"\nautomaticallyFill="+t+"\nskip_basicauth="+s+"\nfrom_iframe="+r+"\ndesc="+q);var u=!1,m=!1,n=0;!k&&(d.pwprotect||g_prompts.login_site_prompt)?(console_log("FILL : Showing Security Prompt"),security_prompt(function(){setTimeout(function(){var a=get_record(d.aid);fill({tabid:b,acct:a,docid:c,submit:f,doconfirm:e,docnum:g,allowforce:h,skip_pwprotect:!0,manualfill:j,automaticallyFill:null,skip_basicauth:null,from_iframe:r,desc:"fill_PW"})},100)},null,null,!0,d.aid,!0)):get_selected_tab(null,function(a){if(!s&&
t&&(h||1==d.basic_auth)&&gettabid(a)==b&&g_ischrome&&have_binary_function("fill_basicauth")){a=getusernamefromacct(d);var p=getpasswordfromacct(d);if(""!=a||""!=p){write_history({cmd:"check_autologin1",tabid:b,aid:d.aid,submit:l});var l=check_autologin(f,d),q=lp_gettld_url(d.url),v=lp_gettld_url(g_basicauth_origurl);compare_tlds(q,v)&&(q=v);call_binary_function("fill_basicauth",a,p,h?!0:!1,q,l?!0:!1,function(a){a?g_basicauth_found=!1:fill({tabid:b,acct:d,docid:c,submit:f,doconfirm:e,docnum:g,allowforce:h,
skip_pwprotect:k,manualfill:j,automaticallyFill:t,skip_basicauth:!0,desc:"FILLBASIC"})});return}}is_guiless()&&(t=1);q=d.tld;customjs_has_humanize(d.aid)&&(u=!0);customjs_has_force_fillbest(d.aid)&&(m=!0);l=d.fields;p=l.length?l.length:0;e=1==e?1:0;h=h?1:0;r=r?1:0;a=null!=d.sharedfromaid&&""!=d.sharedfromaid&&"0"!=d.sharedfromaid&&"null"!=d.sharedfromaid?1:0;if(0!=p){for(p=q=0;p<l.length;p++)l[p]&&"password"==l[p].type&&q++;q=!d.save_all&&0==q;v=[];for(p=0;p<l.length;p++)if(l[p]&&(d.save_all||!(1==
e&&"password"!=l[p].type&&!h&&!q))){var w=l[p],A=w.value;if(!(""!=w.name&&"undefined"!=typeof v[w.name+A+w.type])){v[w.name+A+w.type]=1;var y=w.type;if(!("undefined"!=typeof d.captcha_id&&""!=d.captcha_id&&d.captcha_id==w.name&&"text"==y)){if("text"==y||"password"==y||"email"==y||"tel"==y||"textarea"==y||"url"==y)A=lpmdec_acct(A,!0,d,g_shares);if(""!=A){verbose_log("Sending FillRequest: "+p+"\ntype="+y+"\nname="+w.name+"\nvalue=<hidden>");var B="undefined"!=typeof g_launches[b]&&g_launches[b]&&g_launches[b]==
d.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[d.aid]&&25E3>=(new Date).getTime()-g_last_launch[d.aid]?!0:!1,C={from:"fillfield_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;u&&n++;fillfieldCS(b,g,d.aid,{reqinfo:C,docid:c,sharedsite:a,automaticallyFill:t,is_launch:B,manualfill:j,name:w.name,value:A,type:y,checked:w.checked,otherfield:w.otherfield,doconfirm:e||d.save_all&&"password"==y?1:2,allowforce:h,sharedsite:a,from_iframe:r,
humanize:u,delaysecs:n,force_fillbest:m},f)}}}}}else h&&(console_log("no fields. finding best match "+getusernamefromacct(d)+" and <hidden>"),B="undefined"!=typeof g_launches[b]&&g_launches[b]&&g_launches[b]==d.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[d.aid]&&25E3>=(new Date).getTime()-g_last_launch[d.aid]?!0:!1,console_log("Sending fillbest from A reqindex="+g_reqindex),C={from:"fillbest_A",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},
++g_reqindex,fillbestCS(b,g,d.aid,{reqinfo:C,docid:c,updatefields:1,addurid:0,sharedsite:a,automaticallyFill:t,is_launch:B,humanize:u}));h&&logLoginAndCheckWeakPassword(b,d);1!=e&&(l=check_autologin(f,d),"undefined"!=typeof AUTOSUBMIT&&(l=!0),write_history({cmd:"check_autologin2",tabid:b,aid:d.aid,submit:l,docnum:g}),"string"==typeof d.custom_js&&""!=d.custom_js&&sendCS(b,{cmd:"run_custom_js",docid:c,custom_js:d.custom_js,username:getusernamefromacct(d),password:lpmdec_acct(d.password,!0,d,g_shares),
onlyfill:l?0:1,loc:3},g),("string"!=typeof d.custom_js||-1==d.custom_js.indexOf("lpdontsubmit"))&&l&&submitCS(b,g,d.aid,{docid:c}))})}
function logLoginAndCheckWeakPassword(a,b){get_all_windows({populate:!0},function(d){for(var c=0;c<d.length;c++)for(var f=0;f<get_tabs_length(d[c]);f++){var e=get_tabs(d[c])[f];if(gettabid(e)==a&&(checkWeakDuplicateBreached(b,a,lp_gettld_url(gettaburl(e))),(g_loglogins||LPISLOC)&&"undefined"==typeof g_loggedLogins[b.aid]))g_loggedLogins[b.aid]="1",loglogintab(b.aid,e)}})}function showpageoverlay(a){sendCS(a,{cmd:"showoverlay",urlprefix:getchromeurl("",!0)})}
function check_autologin(a,b){var d=!1;if(a)d=!0;else if(b.autologin){var c=(new Date).getTime(),f=parseInt(lpGetPref("autoautoVal",25));if(isNaN(f)||""==f||0>=f)f=25;f=c-1E3*f;"undefined"==typeof b.last_auto_login||isNaN(b.last_auto_login)||b.last_auto_login<f?(console_log("Launching autologin"),b.last_auto_login=c,d=!0):console_log("last autologin too soon!")}return d}
function fillfieldsconfirm(a){if(!a||!lploggedin)return!1;var b=a.url,d="undefined"!=typeof a.topurl?a.topurl:"",c=lp_gettld_url(b),f=a.result,e=a.aid,g=a.docid,h=a.tabid,k=a.doconfirm,s=a.from_iframe?!0:!1,r=a.manualfill,q=a.allowforce,j=!1,t="undefined"!=typeof a.automaticallyFill?a.automaticallyFill:1,q=a.force_fillbest,u=a.name,m=get_record(e);if(!m)return!1;u&&(g_fillfield_confirm_perfield[u]=f?!0:!1);if(hasNeverAutologin(b,c)||d&&d!=b&&hasNeverAutologin(d,c))j=!0;if(f&&(logLoginAndCheckWeakPassword(h,
m),2==k))return s&&(r&&!j)&&sendCS(h,{cmd:"conditionalforcefill",reqinfo:x,username:getusernamefromacct(m),password:getpasswordfromacct(m),aid:m.aid,sharedsite:n,automaticallyFill:t,from_iframe:s},a.docnum),!0;if(j)return!1;var n=null!=m.sharedfromaid&&""!=m.sharedfromaid&&"0"!=m.sharedfromaid&&"null"!=m.sharedfromaid?1:0;if(m.save_all){if(!f&&sufficient_condition_fill_saveall(m))return console.log("sufficient successful fills, ignoring failed fill result on saveall fill"),!0;if(!f||r){b="undefined"!=
typeof g_launches[h]&&g_launches[h]&&g_launches[h]==m.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[m.aid]&&25E3>=(new Date).getTime()-g_last_launch[m.aid]?!0:!1;console_log("Sending fillbest from B reqindex="+g_reqindex);var x={from:"fillbest_B",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())};++g_reqindex;fillbestCS(h,a.docnum,m.aid,{reqinfo:x,docid:g,updatefields:0,addurid:0,sharedsite:n,automaticallyFill:t,is_launch:b,saveall:m.saveall?
!0:!1})}}else if(f){m=get_record(e);r=q=null;s&&a.manualfill&&(q=r=!0);var p;fill({tabid:h,acct:m,docid:g,submit:null,doconfirm:!1,docnum:a.docnum,allowforce:q,skip_pwprotect:!0,manualfill:r,automaticallyFill:t,skip_basicauth:!1,from_iframe:s,desc:"FILL_F5"});delete g_fillfieldsmatches[b];delete g_fillfieldsmatchescurridx[b]}else if(a.allowforce||q&&!g_fillfield_did_fillbest[h.toString()]&&!sufficient_condition_fill_nonsaveall(m))q&&(g_fillfield_did_fillbest[h.toString()]=!0),b="undefined"!=typeof g_launches[h]&&
g_launches[h]&&g_launches[h]==m.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[m.aid]&&25E3>=(new Date).getTime()-g_last_launch[m.aid]?!0:!1,console_log("Sending fillbest from C reqindex="+g_reqindex),x={from:"fillbest_C",index:g_reqindex,time:(new Date).getTime(),uniqid:Math.floor(1E8*Math.random())},++g_reqindex,fillbestCS(h,a.docnum,e,{reqinfo:x,docid:g,updatefields:0,addurid:r?1:0,sharedsite:n,automaticallyFill:t,is_launch:b,force_fillbest:q});else{if(e=g_fillfieldsmatches[b]){r=
!1;for(m=0;m<e.length;m++){n=e[m].aid;if(r){(m=g_sites[n])&&(p=!1);fill({tabid:h,acct:m,docid:g,submit:null,doconfirm:!0,docnum:a.docnum,allowforce:null,skip_pwprotect:!0,manualfill:null,automaticallyFill:t,skip_basicauth:p,from_iframe:s,desc:"FILL_F6"});return}m==g_fillfieldsmatchescurridx[b]&&(g_fillfieldsmatchescurridx[b]++,r=!0)}}delete g_fillfieldsmatches[b];delete g_fillfieldsmatchescurridx[b]}return!0}
function web2plug(a){"2"==a.rsa?(g_local_key=AES.hex2bin(a.key),g_local_key_hex=a.key,g_local_key_hash=SHA256(g_local_key),rsa_userchangedpassword(),a=opendb(),createDataTable(a),a&&!LPISLOC&&a.transaction(function(a){a.executeSql("DELETE FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"accts"],function(){},function(a,b){console_log(b)})}),lpWriteKeyFile()):""!=g_username&&null!=g_username&&g_username!=a.username?loggedOut(!1,"web2plug"):(g_local_key=AES.hex2bin(a.key),
g_local_key_hex=a.key,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile())}function recover(a,b,d,c){var f=lpParseUri(b);b=f.directory;f=f.file;b=b.replace(/^\/~[^/]*/,"");""!=b&&"/"!=b&&"/sso/"!=b||"recover.php"==f&&GetOTPHash(null,a,d,c)}
function loginfromwebsite(a){if(""!=a.wxusername&&""!=a.keyhex){var b=opendb();createSavedLoginsTable(b);b&&b.transaction(function(c){1==a.rememberemail?(L("remembering email"),set_default_login_username(a.wxusername)):L("not remembering email");c.executeSql("SELECT * FROM LastPassSavedLogins2 WHERE username = ? AND password != ''",[a.wxusername],function(c,d){if(0<d.rows.length){var f=d.rows.item(0).password,k=function(c){var d=get_key_iterations(a.wxusername);make_lp_key_iterations(a.wxusername,
c,d,function(c){AES.bin2hex(c)!=a.keyhex&&b.transaction(function(b){b.executeSql("UPDATE LastPassSavedLogins2 SET password = '' WHERE username = ?",[a.wxusername],function(){},function(a,b){console_log(b)})})})};1==d.rows.item(0)["protected"]?unprotect_data(f,!1,k):2==d.rows.item(0)["protected"]&&k(lpdec(f,AES.hex2bin(SHA256(a.wxusername))))}},function(){})});var d=AES.hex2bin(a.keyhex),c=null!=g_local_key?AES.bin2hex(g_local_key):"";if(!lploggedin||!(g_username==a.wxusername&&c==a.keyhex))lploggedin&&
g_username==a.wxusername?(g_local_key=d,g_local_key_hex=a.keyhex,g_local_key_hash=SHA256(g_local_key)):(lploggedin&&""!=g_username&&loggedOut(!1,"differentuser"),""!=a.wxsessid&&(lp_phpsessid=a.wxsessid),g_local_key=d,g_local_key_hex=a.keyhex,g_local_key_hash=SHA256(g_local_key),lpWriteKeyFile(),LP.lplogincheck(!0,null,a.wxusername,a.wxhash))}else lploggedin||LP.lplogincheck(!0)}
function reorderOnURL(a,b,d,c){var f=lpParseUri(b),e=lpcanonizeUrl(b,f),g="string"==typeof f.path?f.path.split("/"):[],h=lp_gettld_url(b),k=[],s;for(s in a)if(check_ident_aid(s)&&(a=g_sites[s],!("undefined"==typeof a||"undefined"==typeof a.url)))if(a.save_all||!d||!(""==a.unencryptedUsername&&""==a.password))if(!c||accthaspassword(a)){var r=lpParseUri(a.url);a.realmmatch=(b==g_basicauth_url||b==g_basicauth_origurl)&&(lpmdec_acct(a.realm_data,!0,a,g_shares)==g_basicauth_realm||g_basicauth_found&&""==
g_basicauth_realm&&1==a.basic_auth);a.servermatch=f.host==r.host;a.portmatch=compare_ports(f,r);a.serverportmatch=a.servermatch&&a.portmatch?1:0;a.usernamematch="undefined"!=typeof g_username_vals[b]&&""!=g_username_vals[b]&&g_username_vals[b]==a.unencryptedUsername;a.urlmatch=lpcanonizeUrl(a.url)==e?!0:!1;var r="string"==typeof r.path?r.path.split("/"):[],q;for(q=0;q<g.length&&q<r.length&&r[q]==g[q];q++);a.pathlevelmatch=q;a.fieldmatchcount=0;k.push(a)}k.sort(lp_aids_sort_func);return k=checkurlrules(g_urlrules,
k,h,"string"==typeof f.path?f.path:"",f.host,g_sites,get_port(f))}
function lp_aids_sort_func(a,b){return a.realmmatch!=b.realmmatch?a.realmmatch?-1:1:a.usernamematch!=b.usernamematch?a.usernamematch?-1:1:a.fav!=b.fav?"1"==a.fav?-1:1:a.urlmatch!=b.urlmatch?a.urlmatch?-1:1:a.serverportmatch&&b.serverportmatch&&a.pathlevelmatch!=b.pathlevelmatch?a.pathlevelmatch>b.pathlevelmatch?-1:1:a.serverportmatch!=b.serverportmatch?a.serverportmatch?-1:1:a.servermatch!=b.servermatch?a.servermatch?-1:1:a.fieldmatchcount!=b.fieldmatchcount?a.fieldmatchcount>b.fieldmatchcount?-1:
1:a.last_touch!=b.last_touch?a.last_touch>b.last_touch?-1:1:a.name!=b.name?a.name<b.name?-1:1:0}function lp_sort_case_insensitive_name(a,b){a=a.name.toLowerCase();b=b.name.toLowerCase();return a<b?-1:1}
function launchautologin(a,b){if(check_ident_aid(a)){var d=g_sites[a];d&&(!b&&(d.pwprotect||g_prompts.login_site_prompt)?d.pwprotect&&needs_secure_reprompt(d)?security_prompt(function(){launchautologin(a,!0)},null,null,!0,d.aid,!1):security_prompt(function(){launchautologin(a,!0)}):(g_last_launch[d.aid]=(new Date).getTime(),openURL(d.url,function(a,b){g_launches[gettabid(a)]=b},d.aid)))}}
function is_max_frames_exceeded(a,b){var d=10;if(null==b)return!0;try{var c=g_CS_tops[a],f=g_CS[a][c],e="",e=g_ischrome&&f?lp_gettld_url(f.sender.tab.url):lp_gettld_url(gettaburl(f));"undefined"==typeof c?L("still waiting for topdoc to register for [tab:"+a+"] tld="+e):L("topdoc="+c+" tld="+e);e&&"dailykos.com"==e&&(d=40)}catch(g){console.error("is_max_frames_exceeded: "+g)}debug&&(c=count_cs_for_tabid(a),0<c&&console.warn("is_max_frames_exceeded: CS table count="+c+", global g_CS_count="+g_CS_count[a]),
dumpinfo_for_tabid(a));g_skip_ad_frames&&(d=25);return b[a]>d}
function fillbestCS(a,b,d,c){var f=get_record(d);if("undefined"==typeof a||!f)return!1;c||(c={aid:d});c.cmd="fillbest";"undefined"==typeof c.clearfilledfieldsonlogoff&&(c.clearfilledfieldsonlogoff=lpGetPref("clearfilledfieldsonlogoff",0));"undefined"==typeof c.realurl&&(c.realurl=f.url);"undefined"==typeof c.username&&(c.username=getusernamefromacct(f));"undefined"==typeof c.password&&(c.password=getpasswordfromacct(f));"undefined"==typeof c.custom_js&&(c.custom_js=f.custom_js);"undefined"==typeof c.domains&&
(c.domains=getacceptabletlds(f.url));"undefined"==typeof c.is_launch&&(c.is_launch="undefined"!=typeof g_launches[a]&&g_launches[a]&&g_launches[a]==f.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[f.aid]&&25E3>=(new Date).getTime()-g_last_launch[f.aid]?!0:!1);"undefined"==typeof c.automaticallyFill&&(c.automaticallyFill=1);"undefined"==typeof c.updatefields&&(c.updatefields=0);"undefined"==typeof c.addurid&&(c.addurid=0);"undefined"==typeof c.aid&&(c.aid=d);"undefined"==
typeof c.sharedsite&&(c.sharedsite=null!=f.sharedfromaid&&""!=f.sharedfromaid&&"0"!=f.sharedfromaid&&"null"!=f.sharedfromaid?1:0);"undefined"==typeof c.dontfillautocompleteoff&&(c.dontfillautocompleteoff=getInt(lpGetPref("dontfillautocompleteoff",0)));"undefined"==typeof c.saveall&&(c.saveall=f.saveall?!0:!1);write_history({cmd:"fillbestCS",tabid:a,docnum:b,aid:d,username:c.username,force_fillbest:c.force_fillbest});sendCS(a,c,b);return!0}
function fillfieldCS(a,b,d,c,f){var e=get_record(d);if("undefined"==typeof a||!e)return!1;c||(c={aid:d});c.cmd="fillfield";"undefined"==typeof c.clearfilledfieldsonlogoff&&(c.clearfilledfieldsonlogoff=lpGetPref("clearfilledfieldsonlogoff",0));"undefined"==typeof c.dontfillautocompleteoff&&(c.dontfillautocompleteoff=getInt(lpGetPref("dontfillautocompleteoff",0)));"undefined"==typeof c.realurl&&(c.realurl=e.url);"undefined"==typeof c.aid&&(c.aid=d);"undefined"==typeof c.tabid&&(c.tabid=a);"undefined"==
typeof c.custom_js&&(c.custom_js=e.custom_js);"undefined"==typeof c.domains&&(c.domains=getacceptabletlds(e.url));"undefined"==typeof c.is_launch&&(c.is_launch="undefined"!=typeof g_launches[a]&&g_launches[a]&&g_launches[a]==e.aid&&"undefined"!=typeof g_last_launch&&"undefined"!=typeof g_last_launch[e.aid]&&25E3>=(new Date).getTime()-g_last_launch[e.aid]?!0:!1);"undefined"==typeof c.automaticallyFill&&(c.automaticallyFill=1);"undefined"==typeof c.from_iframe&&(c.from_iframe=0);"undefined"==typeof c.formname&&
(c.formname="");"undefined"==typeof c.type&&(c.type="text");"undefined"==typeof c.doconfirm&&(c.doconfirm=2);if("undefined"==typeof c.delaysecs||!parseInt(c.delaysecs))c.delaysecs=0;""!=e.custom_js&&(c.username=getusernamefromacct(e),c.password=getpasswordfromacct(e),c.onlyfill=f?0:1);if("undefined"==typeof c.name||"undefined"==typeof c.value)return console_error("missing required fields!"),!1;write_history({cmd:"fillfieldCS",tabid:a,docnum:b,aid:c.aid,name:c.name,custom_js:c.custom_js,manualfill:c.manualfill,
is_launch:c.is_launch});c.humanize&&c.delaysecs?setTimeout(function(){sendCS(a,c,b)},1E3*c.delaysecs):sendCS(a,c,b);return!0}
function submitCS(a,b,d,c){var f=get_record(d);if("undefined"==typeof a||!f)return!1;var e="undefined"!=typeof f.submit_id?f.submit_id:"",g="undefined"!=typeof f.submit_html?f.submit_html:"",h="undefined"!=typeof f.submit_js?f.submit_js:"";c||(c={aid:d});c.cmd="submit";"undefined"==typeof c.aid&&(c.aid=d);"undefined"==typeof c.custom_js&&(c.custom_js=f.custom_js);"undefined"==typeof c.submit_id&&(c.submit_id=e);"undefined"==typeof c.submit_html&&(c.submit_html=g);"undefined"==typeof c.submit_js&&
(c.submit_js=h);if("undefined"==typeof c.delaysecs||!parseInt(c.delaysecs))c.delaysecs=0;is_guiless()&&"bankofamerica.com"==lp_gettld_url(f.url)?pass:(write_history({cmd:"submitCS",tabid:a,docnum:b,aid:d}),c.humanize&&c.delaysecs?setTimeout(function(){sendCS(a,c,b)},1E3*c.delaysecs):sendCS(a,c,b));return!0}function customjs_has_humanize(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("lphumanize")?!0:!1}
function customjs_has_dontsubmit(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("lpdontsubmit")?!0:!1}function check_for_frame_mismatch_ok(a,b,d,c){if(!d||!a)return!1;var f=0;"undefined"!=typeof b&&b&&(f=b);return f&&!frame_and_topdoc_has_same_domain(a)&&(ftd_report_error(a,c?c:"unknown"),!lpConfirmYesNo(d+"\n\n"+lp_gettld_url(ftd_get_frameparenturl(a))))?!1:!0}
function set_casper_active_tab(a,b){g_iscasper&&a&&(a.casper_activeTab=g_CS[g_CS_tops[b]]);return!0}function get_casper_active_tab(a){return g_iscasper&&a&&a.casper_activeTab?a.casper_activeTab:null}function count_fillfield_confirms(){return Object.keys(g_fillfield_confirm_perfield).length}
function sufficient_condition_fill_saveall(a){if(!a)return!1;var b,d=null,c=null;if(3<=count_fillfield_confirms()){for(b in a.fields)if(a.fields.hasOwnProperty(b)&&a.fields[b]&&("text"==a.fields[b].type||"email"==a.fields[b].type||"tel"==a.fields[b].type)&&""!=a.fields[b].value){d=a.fields[b].name;break}for(b in a.fields)if(a.fields.hasOwnProperty(b)&&a.fields[b]&&"password"==a.fields[b].type&&""!=a.fields[b].value){c=a.fields[b].name;break}if(d&&c)return!0}return!1}
function customjs_has_force_fillbest(a){a=get_record(a);return!a?!1:"string"==typeof a.custom_js&&0<=a.custom_js.indexOf("__lpforcefillbest")?!0:!1}function sufficient_condition_fill_nonsaveall(a){if(!a)return!1;var b=null,d=null;return 2<=count_fillfield_confirms()&&(b=getusernamefromacct(a),d=getpasswordfromacct(a),b&&d)?!0:!1};
